(tree (tag start "html" lang "en") (tree (tag start "head") (tag start-end "meta" http-equiv "Content-Type" content "text/html; charset=ISO-8859-1") (tree (tag start "title") "HTML 4.01 Specification") (tag start-end "link" rel "next" href "about.html") (tag start-end "link" rel "contents" href "cover.html#minitoc") (tag start-end "link" rel "STYLESHEET" href "style/default.css" type "text/css")) (tree (tag start "body") (tree (tag start "div" class "navbar" align "center") "&nbsp;" (tree (tag start "a" href "about.html") "next") "&nbsp;
" (tree (tag start "a" href "#minitoc") "table of contents") "&nbsp; " (tree (tag start "a" href "index/elements.html") "elements") "&nbsp; " (tree (tag start "a" href "index/attributes.html") "attributes") "&nbsp; " (tree (tag start "a" href "index/list.html") "index") (tag start-end "hr")) (tree (tag start "div" class "head") (tree (tag start "p") (tree (tag start "a" href "http://www.w3.org/") (tag start-end "img" height "48" width "72" alt "W3C" src "http://www.w3.org/Icons/w3c_home"))) (tree (tag start "h1") "HTML 4.01 Specification") (tree (tag start "h2") "W3C Recommendation 24 December 1999") (tree (tag start "dl") (tree (tag start "dt") "This version:") (tree (tag start "dd") (tree (tag start "a" href "http://www.w3.org/TR/1999/REC-html401-19991224") "http://www.w3.org/TR/1999/REC-html401-19991224")) (tree (tag start "dd") "(" (tree (tag start "a" href "html40.txt") "plain text [794Kb]") ", " (tree (tag start "a" href "html40.tgz") "gzip'ed
tar archive of HTML files [371Kb]") ", " (tree (tag start "a" href "html40.zip") "a .zip archive of
HTML files [405Kb]") ", " (tree (tag start "a" href "html40.ps.gz") "gzip'ed Postscript file [746Kb,
389 pages]") ", " (tree (tag start "a" href "html40.pdf.gz") "gzip'ed PDF file [963Kb]") ")") (tree (tag start "dt") "Latest version of HTML 4.01:") (tree (tag start "dd") (tree (tag start "a" href "http://www.w3.org/TR/html401") "http://www.w3.org/TR/html401")) (tree (tag start "dt") "Latest version of HTML 4:") (tree (tag start "dd") (tree (tag start "a" href "http://www.w3.org/TR/html4") "http://www.w3.org/TR/html4")) (tree (tag start "dt") "Latest version of HTML:") (tree (tag start "dd") (tree (tag start "a" href "http://www.w3.org/TR/html") "http://www.w3.org/TR/html")) (tree (tag start "dt") "Previous version of HTML 4.01:") (tree (tag start "dd") (tree (tag start "a" href "http://www.w3.org/TR/1999/PR-html40-19990824 ") "http://www.w3.org/TR/1999/PR-html40-19990824")) (tree (tag start "dt") "Previous HTML 4 Recommendation:") (tree (tag start "dd") (tree (tag start "a" href "http://www.w3.org/TR/1998/REC-html40-19980424") "http://www.w3.org/TR/1998/REC-html40-19980424")) (tree (tag start "dt") "Editors:") (tree (tag start "dd") (tree (tag start "a" href "http://www.w3.org/People/Raggett") "Dave Raggett") "&lt;" (tree (tag start "a" href "mailto:dsr@w3.org") "dsr@w3.org") "&gt;") (tree (tag start "dd") "Arnaud Le Hors, W3C") (tree (tag start "dd") "Ian Jacobs, W3C")) (tree (tag start "p" class "copyright") (tree (tag start "a" href "http://www.w3.org/Consortium/Legal/ipr-notice#Copyright") "Copyright") "&copy;1997-1999 " (tree (tag start "a" href "http://www.w3.org/") (tree (tag start "abbr" title "World Wide Web 
Consortium") "W3C")) (tree (tag start "sup") "&reg;") "(" (tree (tag start "a" href "http://www.lcs.mit.edu/") (tree (tag start "abbr" title "Massachusetts Institute of
Technology") "MIT")) ", " (tree (tag start "a" href "http://www.inria.fr/") (tree (tag start "abbr" lang "fr" title "Institut National de Recherche en Informatique et Automatique") "INRIA")) ", " (tree (tag start "a" href "http://www.keio.ac.jp/") "Keio") "), All Rights
Reserved. W3C " (tree (tag start "a" href "http://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer") "liability") ",
" (tree (tag start "a" href "http://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks") "trademark") ", " (tree (tag start "a" href "http://www.w3.org/Consortium/Legal/copyright-documents-19990405") "document
use") "and " (tree (tag start "a" href "http://www.w3.org/Consortium/Legal/copyright-software-19980720") "software
licensing") "rules apply.")) (tag start-end "hr" title "Separator from Header") (tree (tag start "h2") "Abstract") (tree (tag start "p") "This specification defines the HyperText Markup Language (HTML), the
publishing language of the World Wide Web. This specification defines HTML
4.01, which is a subversion of HTML 4. In addition to the text, multimedia, and
hyperlink features of the previous versions of HTML (HTML 3.2 " (tree (tag start "a" rel "biblioentry" href "./references.html#ref-HTML32" class "informref") "[HTML32]") "and HTML 2.0 " (tree (tag start "a" rel "biblioentry" href "./references.html#ref-RFC1866" class "informref") "[RFC1866]") "), HTML 4
supports more multimedia options, scripting languages, style sheets, better
printing facilities, and documents that are more accessible to users with
disabilities. HTML 4 also takes great strides towards the internationalization
of documents, with the goal of making the Web truly World Wide.") (tree (tag start "p") "HTML 4 is an SGML application conforming to International Standard ISO 8879
-- Standard Generalized Markup Language " (tree (tag start "a" rel "biblioentry" href "./references.html#ref-ISO8879" class "normref") "[ISO8879]") ".") (tree (tag start "h2") "Status of this document") (tree (tag start "p") (tree (tag start "em") "This section describes the status of this document at the time of its
publication. Other documents may supersede this document. The latest status of
this document series is maintained at the W3C.")) (tree (tag start "p") "This document specifies HTML 4.01, which is part of the HTML 4 line of
specifications. The first version of HTML 4 was HTML 4.0 " (tree (tag start "a" rel "biblioentry" href "./references.html#ref-HTML40" class "informref") "[HTML40]") ", published
on 18 December 1997 and revised 24 April 1998. This specification is the first
HTML 4.01 Recommendation. It includes non-editorial " (tree (tag start "a" href "appendix/changes.html#19991224") "changes since the 24 April version of HTML
4.0") ". There have been some changes to the DTDs, for example. This document
obsoletes previous versions of HTML 4.0, although W3C will continue to make
those specifications and their DTDs available at the W3C Web site.") (tree (tag start "p") "This document has been reviewed by W3C Members and other interested parties
and has been endorsed by the Director as a W3C Recommendation. It is a stable
document and may be used as reference material or cited as a normative
reference from another document. W3C's role in making the Recommendation is to
draw attention to the specification and to promote its widespread deployment.
This enhances the functionality and interoperability of the Web.") (tree (tag start "p") "W3C recommends that user agents and authors (and in particular, authoring
tools) produce HTML 4.01 documents rather than HTML 4.0 documents. W3C
recommends that authors produce HTML 4 documents instead of HTML 3.2 documents.
For reasons of backward compatibility, W3C also recommends that tools
interpreting HTML 4 continue to support HTML 3.2 and HTML 2.0 as well.") (tree (tag start "p") "For information about the next generation of HTML, \"The Extensible HyperText
Markup Language\" " (tree (tag start "a" rel "biblioentry" href "./references.html#ref-XHTML" class "informref") "[XHTML]") ", please refer to the " (tree (tag start "a" href "http://www.w3.org/MarkUp/") "W3C HTML Activity") "and the list of " (tree (tag start "a" href "http://www.w3.org/TR") "W3C Technical Reports") ".") (tree (tag start "p") "This document has been produced as part of the " (tree (tag start "a" href "http://www.w3.org/MarkUp/") "W3C HTML Activity") ". The goals of the " (tree (tag start "a" href "http://www.w3.org/MarkUp/Group/") "HTML Working Group") (tree (tag start "i") "(" (tree (tag start "a" href "http://cgi.w3.org/MemberAccess/") "Members only") ")") "are discussed in the " (tree (tag start "a" href "http://www.w3.org/MarkUp/Group/HTMLcharter") "HTML Working Group
charter") (tree (tag start "i") "(" (tree (tag start "a" href "http://cgi.w3.org/MemberAccess/") "Members
only") ")") ".") (tree (tag start "p") "A list of current W3C Recommendations and other technical documents can be
found at " (tree (tag start "a" href "http://www.w3.org/TR") "http://www.w3.org/TR") ".") (tree (tag start "p") "Public discussion on HTML features takes place on " (tree (tag start "a" href "mailto:www-html@w3.org") "www-html@w3.org") "(" (tree (tag start "a" href "http://lists.w3.org/Archives/Public/www-html/") "archives of
www-html@w3.org") ").") (tree (tag start "h3") "Available languages") (tree (tag start "p") "The English version of this specification is the only normative version.
However, for translations of this document, see " (tree (tag start "a" href "http://www.w3.org/MarkUp/html4-updates/translations") "http://www.w3.org/MarkUp/html4-updates/translations") ".") (tree (tag start "h3") "Errata") (tree (tag start "dl") (tree (tag start "dt") "The list of known errors in this specification is available at:") (tree (tag start "dd") (tree (tag start "a" href "http://www.w3.org/MarkUp/html4-updates/errata") "http://www.w3.org/MarkUp/html4-updates/errata"))) (tree (tag start "p") "Please report errors in this document to " (tree (tag start "a" href "mailto:www-html-editor@w3.org") "www-html-editor@w3.org") ".") (tree (tag start "div" class "toc") (tree (tag start "h2") (tree (tag start "a" name "minitoc") "Quick Table of Contents")) (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html" rel "chapter") "About the HTML 4
Specification")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html" rel "chapter") "Introduction to
HTML 4")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html" rel "chapter") "On SGML and
HTML")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "conform.html" rel "chapter") "Conformance:
requirements and recommendations")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html" rel "chapter") "HTML Document
Representation") (tree (tag start "em") "- Character sets, character encodings, and
entities")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html" rel "chapter") "Basic HTML data
types") (tree (tag start "em") "- Character data, colors, lengths, URIs, content types,
etc.")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html" rel "chapter") "The global
structure of an HTML document") (tree (tag start "em") "- The HEAD and BODY of a
document")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html" rel "chapter") "Language
information and text direction") (tree (tag start "em") "- International considerations for
text")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html" rel "chapter") "Text") (tree (tag start "em") "-
Paragraphs, Lines, and Phrases")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/lists.html" rel "chapter") "Lists") (tree (tag start "em") "-
Unordered, Ordered, and Definition Lists")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html" rel "chapter") "Tables")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html" rel "chapter") "Links") (tree (tag start "em") "-
Hypertext and Media-Independent Links")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html" rel "chapter") "Objects,
Images, and Applets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html" rel "chapter") "Style
Sheets") (tree (tag start "em") "- Adding style to HTML documents")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html" rel "chapter") "Alignment,
font styles, and horizontal rules")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html" rel "chapter") "Frames") (tree (tag start "em") "- Multi-view presentation of documents")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html" rel "chapter") "Forms") (tree (tag start "em") "-
User-input Forms: Text Fields, Buttons, Menus, and more")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html" rel "chapter") "Scripts") (tree (tag start "em") "- Animated Documents and Smart Forms")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/intro.html" rel "chapter") "SGML reference
information for HTML") (tree (tag start "em") "- Formal definition of HTML and
validation")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/sgmldecl.html" rel "chapter") (tree (tag start "span" class "index-def" title "SGML::declaration of HTML 4") "SGML Declaration of HTML
4"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/dtd.html" rel "chapter") (tree (tag start "span" class "index-def" title "strict DTD::definition of|document type definition::strict") "Document Type Definition"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/loosedtd.html" rel "chapter") (tree (tag start "span" class "index-def" title "transitional DTD::definition of|document type 
definition::transitional") "Transitional Document Type Definition"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/framesetdtd.html" rel "chapter") (tree (tag start "span" class "index-def" title "frameset::DTD, definition of|document type 
definition::frameset") "Frameset Document Type Definition"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html" rel "chapter") "Character entity
references in HTML 4"))) (tree (tag start "ol" type "A") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html" rel "chapter") "Changes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html" rel "chapter") "Performance,
Implementation, and Design Notes"))) (tree (tag start "ul" class "toc") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "references.html" rel "chapter") "References")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "index/elements.html" rel "chapter") "Index of
Elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "index/attributes.html" rel "chapter") "Index of
Attributes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "index/list.html" rel "chapter") "Index")))) (tree (tag start "h2") (tree (tag start "a" name "toc") "Full Table of Contents")) (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html" rel "chapter") "About the HTML 4
Specification") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html#h-1.1") "How the specification is
organized")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html#h-1.2") "Document conventions") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html#h-1.2.1") "Elements and
attributes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html#h-1.2.2") "Notes and examples")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html#h-1.3") "Acknowledgments") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html#h-1.3.1") "Acknowledgments for the
current revision")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "about.html#h-1.4") "Copyright Notice")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html" rel "chapter") "Introduction to
HTML 4") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.1") "What is the World Wide
Web?") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.1.1") "Introduction to
URIs")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.1.2") "Fragment
identifiers")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.1.3") "Relative URIs")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.2") "What is HTML?") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.2.1") "A brief history of
HTML")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.3") "HTML 4") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.3.1") "Internationalization")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.3.2") "Accessibility")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.3.3") "Tables")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.3.4") "Compound
documents")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.3.5") "Style sheets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.3.6") "Scripting")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.3.7") "Printing")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.4") "Authoring documents with
HTML 4") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.4.1") "Separate structure and
presentation")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.4.2") "Consider universal
accessibility to the Web")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/intro.html#h-2.4.3") "Help user agents with
incremental rendering")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html" rel "chapter") "On SGML and
HTML") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.1") "Introduction to
SGML")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.2") "SGML constructs used in
HTML") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.2.1") "Elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.2.2") "Attributes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.2.3") "Character
references")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.2.4") "Comments")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.3") "How to read the HTML
DTD") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.3.1") "DTD Comments")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.3.2") "Parameter entity
definitions")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.3.3") "Element
declarations") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.3.3.1") "Content model
definitions")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.3.4") "Attribute
declarations") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.3.4.1") "DTD entities in
attribute definitions")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "intro/sgmltut.html#h-3.3.4.2") (tree (tag start "span" class "index-def" title "boolean attribute|attribute::boolean") "Boolean
attributes"))))))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "conform.html" rel "chapter") "Conformance:
requirements and recommendations") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "conform.html#h-4.1") "Definitions")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "conform.html#h-4.2") "SGML")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "conform.html#h-4.3") (tree (tag start "span" class "index-def" title "text/html") "The text/html content type"))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html" rel "chapter") "HTML Document
Representation") (tree (tag start "em") "- Character sets, character encodings, and entities") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.1") "The Document Character
Set")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.2") "Character encodings") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.2.1") "Choosing an encoding") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.2.1.1") "Notes on specific
encodings")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.2.2") "Specifying the character
encoding")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.3") "Character references") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.3.1") "Numeric character
references")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.3.2") "Character entity
references")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "charset.html#h-5.4") "Undisplayable
characters")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html" rel "chapter") "Basic HTML data
types") (tree (tag start "em") "- Character data, colors, lengths, URIs, content types, etc.") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.1") "Case information")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.2") "SGML basic types")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.3") "Text strings")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.4") "URIs")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.5") "Colors") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.5.1") "Notes on using colors")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.6") "Lengths")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.7") "Content types (MIME
types)")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.8") "Language codes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.9") "Character encodings")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.10") "Single characters")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.11") "Dates and times")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.12") "Link types")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.13") "Media descriptors")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.14") "Script data")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.15") "Style sheet data")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "types.html#h-6.16") "Frame target names")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html" rel "chapter") "The global
structure of an HTML document") (tree (tag start "em") "- The HEAD and BODY of a document") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.1") "Introduction to the
structure of an HTML document")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.2") "HTML version
information")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.3") "The " (tree (tag start "samp" class "einst2") "HTML") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.4") "The document head") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.4.1") "The " (tree (tag start "samp" class "einst2") "HEAD") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.4.2") "The " (tree (tag start "samp" class "einst2") "TITLE") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.4.3") "The " (tree (tag start "samp") "title") "attribute")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.4.4") "Meta data") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.4.4.1") "Specifying meta
data")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.4.4.2") "The " (tree (tag start "samp" class "einst2") "META") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.4.4.3") "Meta data
profiles")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.5") "The document body") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.5.1") "The " (tree (tag start "samp" class "einst2") "BODY") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.5.2") "Element identifiers:
the " (tree (tag start "samp") "id") "and " (tree (tag start "samp") "class") "attributes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.5.3") "Block-level and inline
elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.5.4") "Grouping elements: the
" (tree (tag start "samp" class "einst2") "DIV") "and " (tree (tag start "samp" class "einst2") "SPAN") "elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.5.5") "Headings: The " (tree (tag start "samp" class "einst2") "H1") ", " (tree (tag start "samp" class "einst2") "H2") ", " (tree (tag start "samp" class "einst2") "H3") ", " (tree (tag start "samp" class "einst2") "H4") ", " (tree (tag start "samp" class "einst2") "H5") ",
" (tree (tag start "samp" class "einst2") "H6") "elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/global.html#h-7.5.6") "The " (tree (tag start "samp" class "einst2") "ADDRESS") "element")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html" rel "chapter") "Language
information and text direction") (tree (tag start "em") "- International considerations for
text") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.1") "Specifying the language
of content: the " (tree (tag start "samp") "lang") "attribute") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.1.1") (tree (tag start "span" class "index-def" title "language::codes to specify") "Language codes"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.1.2") "Inheritance of
language codes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.1.3") "Interpretation of
language codes")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.2") "Specifying the
direction of text and tables: the " (tree (tag start "samp") "dir") "attribute") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.2.1") "Introduction to the
bidirectional algorithm")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.2.2") "Inheritance of text
direction information")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.2.3") "Setting the direction
of embedded text")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.2.4") "Overriding the
bidirectional algorithm: the " (tree (tag start "samp" class "einst2") "BDO") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.2.5") "Character references
for directionality and joining control")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/dirlang.html#h-8.2.6") "The effect of style
sheets on bidirectionality")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html" rel "chapter") "Text") (tree (tag start "em") "-
Paragraphs, Lines, and Phrases") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.1") (tree (tag start "span" class "index-def" title "white space") "White space"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.2") "Structured text") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.2.1") "Phrase elements: " (tree (tag start "samp" class "einst2") "EM") ", " (tree (tag start "samp" class "einst2") "STRONG") ", " (tree (tag start "samp" class "einst2") "DFN") ", " (tree (tag start "samp" class "einst2") "CODE") ", " (tree (tag start "samp" class "einst2") "SAMP") ", " (tree (tag start "samp" class "einst2") "KBD") ", " (tree (tag start "samp" class "edef") "VAR") ",
" (tree (tag start "samp" class "einst2") "CITE") ", " (tree (tag start "samp" class "einst2") "ABBR") ", and " (tree (tag start "samp" class "einst2") "ACRONYM"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.2.2") "Quotations: The " (tree (tag start "samp" class "einst2") "BLOCKQUOTE") "and " (tree (tag start "samp" class "einst2") "Q") "elements") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.2.2.1") "Rendering
quotations")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.2.3") "Subscripts and
superscripts: the " (tree (tag start "samp" class "edef") "SUB") "and " (tree (tag start "samp" class "einst2") "SUP") "elements")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.3") "Lines and Paragraphs") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.3.1") "Paragraphs: the " (tree (tag start "samp" class "einst2") "P") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.3.2") "Controlling line
breaks") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.3.2.1") "Forcing a line break:
the " (tree (tag start "samp" class "einst2") "BR") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.3.2.2") "Prohibiting a line
break")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.3.3") "Hyphenation")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.3.4") "Preformatted text: The
" (tree (tag start "samp" class "einst2") "PRE") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.3.5") "Visual rendering of
paragraphs")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/text.html#h-9.4") "Marking document changes:
The INS and DEL elements")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/lists.html" rel "chapter") "Lists") (tree (tag start "em") "-
Unordered, Ordered, and Definition Lists") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/lists.html#h-10.1") "Introduction to
lists")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/lists.html#h-10.2") (tree (tag start "span" class "index-def" title "list::unordered") "Unordered lists") "(" (tree (tag start "samp" class "einst2") "UL") "), " (tree (tag start "span" class "index-def" title "list::ordered") "ordered
lists") "(" (tree (tag start "samp" class "einst2") "OL") "), and list items (" (tree (tag start "samp" class "einst2") "LI") ")")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/lists.html#h-10.3") (tree (tag start "span" class "index-def" title "list::definition list") "Definition lists") ": the " (tree (tag start "samp" class "einst2") "DL") ", " (tree (tag start "samp" class "einst2") "DT") ", and " (tree (tag start "samp" class "einst2") "DD") "elements") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/lists.html#h-10.3.1") "Visual rendering of
lists")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/lists.html#h-10.4") "The " (tree (tag start "samp" class "einst2") "DIR") "and " (tree (tag start "samp" class "einst2") "MENU") "elements")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html" rel "chapter") "Tables") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.1") "Introduction to
tables")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2") "Elements for
constructing tables") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.1") "The " (tree (tag start "samp" class "einst2") "TABLE") "element") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.1.1") "Table
directionality")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.2") "Table Captions: The
" (tree (tag start "samp" class "einst2") "CAPTION") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.3") "Row groups: the " (tree (tag start "samp" class "einst2") "THEAD") ", " (tree (tag start "samp" class "einst2") "TFOOT") ", and " (tree (tag start "samp" class "einst2") "TBODY") "elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.4") "Column groups: the
" (tree (tag start "samp" class "einst2") "COLGROUP") "and " (tree (tag start "samp" class "einst2") "COL") "elements") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.4.1") "The " (tree (tag start "samp" class "einst2") "COLGROUP") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.4.2") "The " (tree (tag start "samp" class "einst2") "COL") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.4.3") "Calculating the
number of columns in a table")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.4.4") "Calculating the
width of columns")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.5") "Table rows: The " (tree (tag start "samp" class "einst2") "TR") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.6") "Table cells: The
" (tree (tag start "samp" class "einst2") "TH") "and " (tree (tag start "samp" class "einst2") "TD") "elements") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.2.6.1") "Cells that span
several rows or columns")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.3") "Table formatting by
visual user agents") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.3.1") "Borders and
rules")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.3.2") "Horizontal and
vertical alignment") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.3.2.1") "Inheritance of
alignment specifications")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.3.3") "Cell margins")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.4") "Table rendering by
non-visual user agents") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.4.1") "Associating header
information with data cells")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.4.2") "Categorizing
cells")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.4.3") "Algorithm to find
heading information")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/tables.html#h-11.5") "Sample table")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html" rel "chapter") "Links") (tree (tag start "em") "-
Hypertext and Media-Independent Links") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.1") "Introduction to links
and anchors") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.1.1") "Visiting a linked
resource")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.1.2") "Other link
relationships")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.1.3") "Specifying anchors and
links")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.1.4") "Link titles")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.1.5") "Internationalization
and links")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.2") "The " (tree (tag start "samp" class "einst2") "A") "element") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.2.1") "Syntax of anchor
names")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.2.2") "Nested links are
illegal")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.2.3") "Anchors with the
" (tree (tag start "samp") "id") "attribute")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.2.4") "Unavailable and
unidentifiable resources")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.3") "Document relationships:
the " (tree (tag start "samp" class "einst2") "LINK") "element") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.3.1") "Forward and reverse
links")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.3.2") "Links and external
style sheets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.3.3") "Links and search
engines")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.4") "Path information: the
" (tree (tag start "samp" class "einst2") "BASE") "element") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/links.html#h-12.4.1") (tree (tag start "span" class "index-def" title "URI::resolution of relative|resolution of relative URI") "Resolving relative URIs"))))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html" rel "chapter") "Objects,
Images, and Applets") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.1") "Introduction to
objects, images, and applets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.2") "Including an image:
the " (tree (tag start "samp" class "einst2") "IMG") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.3") "Generic inclusion: the
" (tree (tag start "samp" class "einst2") "OBJECT") "element") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.3.1") "Rules for rendering
objects")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.3.2") "Object
initialization: the " (tree (tag start "samp" class "einst2") "PARAM") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.3.3") "Global naming
schemes for objects")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.3.4") "Object declarations
and instantiations")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.4") "Including an applet:
the " (tree (tag start "samp" class "einst2") "APPLET") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.5") "Notes on embedded
documents")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.6") (tree (tag start "span" class "index-def" title "image map") "Image maps")) (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.6.1") "Client-side image
maps: the " (tree (tag start "samp" class "einst2") "MAP") "and " (tree (tag start "samp" class "einst2") "AREA") "elements") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.6.1.1") "Client-side image
map examples")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.6.2") "Server-side image
maps")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.7") "Visual presentation of
images, objects, and applets") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.7.1") "Width and
height")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.7.2") "White space around
images and objects")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.7.3") "Borders")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.7.4") "Alignment")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "struct/objects.html#h-13.8") "How to specify
alternate text")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html" rel "chapter") "Style
Sheets") (tree (tag start "em") "- Adding style to HTML documents") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.1") "Introduction to style
sheets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.2") "Adding style to
HTML") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.2.1") "Setting the default
style sheet language")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.2.2") "Inline style
information")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.2.3") "Header style
information: the " (tree (tag start "samp" class "einst2") "STYLE") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.2.4") "Media types")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.3") "External style
sheets") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.3.1") "Preferred and
alternate style sheets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.3.2") "Specifying external
style sheets")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.4") "Cascading style
sheets") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.4.1") "Media-dependent
cascades")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.4.2") "Inheritance and
cascading")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.5") "Hiding style data from
user agents")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/styles.html#h-14.6") "Linking to style
sheets with HTTP headers")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html" rel "chapter") "Alignment,
font styles, and horizontal rules") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.1") "Formatting") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.1.1") "Background
color")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.1.2") "Alignment")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.1.3") "Floating
objects") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.1.3.1") "Float an
object")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.1.3.2") "Float text
around an object")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.2") "Fonts") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.2.1") "Font style
elements: the " (tree (tag start "samp" class "einst2") "TT") ", " (tree (tag start "samp" class "einst2") "I") ",
" (tree (tag start "samp" class "einst2-B") "B") ", " (tree (tag start "samp" class "einst2") "BIG") ", " (tree (tag start "samp" class "einst2") "SMALL") ", " (tree (tag start "samp" class "einst2") "STRIKE") ", " (tree (tag start "samp" class "einst2") "S") ", and " (tree (tag start "samp" class "einst2") "U") "elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.2.2") "Font modifier
elements: " (tree (tag start "samp" class "einst2") "FONT") "and " (tree (tag start "samp" class "einst2") "BASEFONT"))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/graphics.html#h-15.3") "Rules: the " (tree (tag start "samp" class "einst2") "HR") "element")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html" rel "chapter") "Frames") (tree (tag start "em") "- Multi-view presentation of documents") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.1") "Introduction to
frames")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.2") "Layout of frames") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.2.1") "The " (tree (tag start "samp" class "einst2") "FRAMESET") "element") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.2.1.1") "Rows and
columns")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.2.1.2") "Nested frame
sets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.2.1.3") "Sharing data among
frames")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.2.2") "The " (tree (tag start "samp" class "einst2") "FRAME") "element") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.2.2.1") "Setting the
initial contents of a frame")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.2.2.2") "Visual rendering
of a frame")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.3") "Specifying target
frame information") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.3.1") "Setting the default
target for links")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.3.2") "Target
semantics")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.4") "Alternate content") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.4.1") "The " (tree (tag start "samp" class "einst2") "NOFRAMES") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.4.2") "Long descriptions of
frames")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "present/frames.html#h-16.5") "Inline frames: the
" (tree (tag start "samp" class "einst2") "IFRAME") "element")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html" rel "chapter") "Forms") (tree (tag start "em") "-
User-input Forms: Text Fields, Buttons, Menus, and more") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.1") "Introduction to
forms")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.2") "Controls") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.2.1") "Control
types")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.3") "The " (tree (tag start "samp" class "einst2") "FORM") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.4") "The " (tree (tag start "samp" class "einst2") "INPUT") "element") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.4.1") "Control types
created with INPUT")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.4.2") "Examples of forms
containing INPUT controls")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.5") "The " (tree (tag start "samp" class "einst2") "BUTTON") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.6") "The " (tree (tag start "samp" class "einst2") "SELECT") ", " (tree (tag start "samp" class "einst2") "OPTGROUP") ", and " (tree (tag start "samp" class "einst2") "OPTION") "elements") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.6.1") "Pre-selected
options")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.7") "The " (tree (tag start "samp" class "einst2") "TEXTAREA") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.8") "The " (tree (tag start "samp" class "einst2") "ISINDEX") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.9") "Labels") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.9.1") "The " (tree (tag start "samp" class "einst2") "LABEL") "element")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.10") "Adding structure to
forms: the " (tree (tag start "samp" class "einst2") "FIELDSET") "and " (tree (tag start "samp" class "einst2") "LEGEND") "elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.11") (tree (tag start "span" class "index-def" title "focus|control::giving focus to") "Giving focus to an
element")) (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.11.1") (tree (tag start "span" class "index-def" title "control::tabbing navigation|tabbing 
navigation|form::navigating through controls") "Tabbing
navigation"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.11.2") (tree (tag start "span" class "index-def" title "access key|control::access key for|accessibility::access
keys") "Access keys"))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.12") "Disabled and
read-only controls") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.12.1") "Disabled
controls")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.12.2") "Read-only
controls")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13") "Form submission") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.1") "Form submission
method")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.2") "Successful
controls")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.3") "Processing form
data") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.3.1") "Step one:
Identify the successful controls")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.3.2") "Step two: Build a
form data set")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.3.3") "Step three:
Encode the form data set")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.3.4") "Step four: Submit
the encoded form data set")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.4") "Form content
types") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.4.1") (tree (tag start "span" class "index-def" title "application/x-www-form-urlencoded|content 
type::application/x-www-form-urlencoded") "application/x-www-form-urlencoded"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/forms.html#h-17.13.4.2") (tree (tag start "span" class "index-def" title "multipart/form-data|content type::multipart/form-data") "multipart/form-data"))))))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html" rel "chapter") "Scripts") (tree (tag start "em") "- Animated Documents and Smart Forms") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.1") "Introduction to
scripts")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.2") "Designing documents
for user agents that support scripting") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.2.1") "The " (tree (tag start "samp" class "einst2") "SCRIPT") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.2.2") "Specifying the
scripting language") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.2.2.1") "The default
scripting language")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.2.2.2") "Local
declaration of a scripting language")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.2.2.3") "References to
HTML elements from a script")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.2.3") "Intrinsic
events")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.2.4") "Dynamic
modification of documents")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.3") "Designing documents
for user agents that don't support scripting") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.3.1") "The " (tree (tag start "samp" class "einst2") "NOSCRIPT") "element")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "interact/scripts.html#h-18.3.2") "Hiding script data
from user agents")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/intro.html" rel "chapter") "SGML reference
information for HTML") (tree (tag start "em") "- Formal definition of HTML and validation") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/intro.html#h-19.1") "Document
Validation")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/intro.html#h-19.2") "Sample SGML
catalog")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/sgmldecl.html" rel "chapter") (tree (tag start "span" class "index-def" title "SGML::declaration of HTML 4") "SGML Declaration of HTML
4")) (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/sgmldecl.html#h-20.1") "SGML
Declaration")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/dtd.html" rel "chapter") (tree (tag start "span" class "index-def" title "strict DTD::definition of|document type definition::strict") "Document Type Definition"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/loosedtd.html" rel "chapter") (tree (tag start "span" class "index-def" title "transitional DTD::definition of|document type 
definition::transitional") "Transitional Document Type Definition"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/framesetdtd.html" rel "chapter") (tree (tag start "span" class "index-def" title "frameset::DTD, definition of|document type 
definition::frameset") "Frameset Document Type Definition"))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html" rel "chapter") "Character entity
references in HTML 4") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html#h-24.1") "Introduction to
character entity references")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html#h-24.2") "Character entity
references for ISO 8859-1 characters") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html#h-24.2.1") "The list of
characters")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html#h-24.3") "Character entity
references for symbols, mathematical symbols, and Greek letters") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html#h-24.3.1") "The list of
characters")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html#h-24.4") "Character entity
references for markup-significant and internationalization characters") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "sgml/entities.html#h-24.4.1") "The list of
characters"))))))) (tree (tag start "ol" type "A") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html" rel "chapter") "Changes") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1") "Changes between 24
April 1998 HTML 4.0 and 24 December 1999 HTML 4.01 versions") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1") "Changes to the
specification") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.1") "General
changes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.2") "On SGML and
HTML")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.3") "HTML Document
Representation")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.4") "Basic HTML data
types")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.5") "Global structure
of an HTML document")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.6") "Language
information and text direction")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.7") "Tables")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.8") "Links")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.9") "Objects, Images,
and Applets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.10") "Style Sheets in
HTML Documents")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.11") "Frames")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.12") "Forms")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.13") "SGML
Declaration")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.14") "Strict
DTD")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.15") "Notes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.1.16") "References")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.2") "Errors that were
corrected")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.3") "Minor typographical
errors that were corrected")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.4") "Clarifications")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.1.5") "Known Browser
problems")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.2") "Changes between 18
December 1997 and 24 April 1998 versions") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.2.1") "Errors that were
corrected")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.2.2") "Minor typographical
errors that were corrected")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3") "Changes between HTML
3.2 and HTML 4.0 (18 December 1997)") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.1") "Changes to
elements") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.1.1") "New
elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.1.2") "Deprecated
elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.1.3") "Obsolete
elements")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.2") "Changes to
attributes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.3") "Changes for
accessibility")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.4") "Changes for meta
data")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.5") "Changes for
text")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.6") "Changes for
links")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.7") "Changes for
tables")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.8") "Changes for images,
objects, and image maps")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.9") "Changes for
forms")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.10") "Changes for style
sheets")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.11") "Changes for
frames")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.12") "Changes for
scripting")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/changes.html#h-A.3.13") "Changes for
internationalization")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html" rel "chapter") "Performance,
Implementation, and Design Notes") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.1") "Notes on invalid
documents")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.2") "Special characters in
URI attribute values") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.2.1") "Non-ASCII characters
in URI attribute values")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.2.2") "Ampersands in URI
attribute values")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3") "SGML implementation
notes") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.1") "Line breaks")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.2") "Specifying non-HTML
data") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.2.1") "Element
content")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.2.2") "Attribute
values")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.3") "SGML features with
limited support")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.4") "Boolean
attributes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.5") "Marked
Sections")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.6") "Processing
Instructions")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.3.7") "Shorthand
markup")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.4") "Notes on helping search
engines index your Web site") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.4.1") "Search robots") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.4.1.1") "The robots.txt
file")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.4.1.2") "Robots and the META
element")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5") "Notes on tables") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.1") "Design rationale") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.1.1") "Dynamic
reformatting")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.1.2") "Incremental
display")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.1.3") "Structure and
presentation")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.1.4") "Row and column
groups")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.1.5") "Accessibility")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.2") "Recommended Layout
Algorithms") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.2.1") "Fixed Layout
Algorithm")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.5.2.2") "Autolayout
Algorithm")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.6") "Notes on forms") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.6.1") "Incremental
display")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.6.2") "Future
projects")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.7") "Notes on scripting") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.7.1") "Reserved syntax for
future script macros") (tree (tag start "ul") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.7.1.1") "Current Practice
for Script Macros")))))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.8") "Notes on
frames")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.9") "Notes on
accessibility")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.10") "Notes on security") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "appendix/notes.html#h-B.10.1") "Security issues for
forms"))))))) (tree (tag start "ul" class "toc") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "references.html" rel "chapter") "References") (tree (tag start "ol") (tree (tag start "li") (tree (tag start "a" class "tocxref" href "references.html#h-1.1") "Normative
references")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "references.html#h-1.2") "Informative
references")))) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "index/elements.html" rel "chapter") "Index of
Elements")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "index/attributes.html" rel "chapter") "Index of
Attributes")) (tree (tag start "li") (tree (tag start "a" class "tocxref" href "index/list.html" rel "chapter") "Index"))) (tree (tag start "div" class "navbar" align "center") (tag start-end "hr") (tree (tag start "a" href "about.html") "next") "&nbsp; " (tree (tag start "a" href "#minitoc") "table of
contents") "&nbsp; " (tree (tag start "a" href "index/elements.html") "elements") "&nbsp; " (tree (tag start "a" href "index/attributes.html") "attributes") "&nbsp; " (tree (tag start "a" href "index/list.html") "index"))))